header-from: ./.config/header.md

version: ""

formatter: markdown table

name: terraform-github-repository-creation

content: |-
  {{ .Header }}
  # terraform-github-repository-creation

  GitHub: [StratusGrid/terraform-github-repository-creation](https://github.com/StratusGrid/terraform-github-repository-creation)

  This module creates GitHub repositories with pre-configured workflow standards. It can use repository templates to provision a repository.

  ## Example

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---
  {{ .Requirements }}
  
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements
sort:
  enabled: true
  by: name
output:
  file: README.md
  mode: replace
